# Generated by Django 2.2.4 on 2019-08-29 09:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='car_images')),
                ('daily_rent', models.IntegerField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.AutoField(primary_key=True, serialize=False)),
                ('booking_start_date', models.DateField(default=datetime.datetime(2019, 8, 29, 11, 29, 16, 238130))),
                ('booking_end_date', models.DateField(default=datetime.datetime(2019, 8, 29, 11, 29, 16, 238130))),
                ('is_approved', models.BooleanField()),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CorrectionApp.Car')),
            ],
        ),
    ]
