# Generated by Django 2.2.4 on 2019-08-30 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0002_bookings_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='bookings',
            name='id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_end_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 11, 49, 26, 491005)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_start_date',
            field=models.DateField(default=datetime.datetime(2019, 8, 30, 11, 49, 26, 491005)),
        ),
    ]
