# Generated by Django 2.2.4 on 2019-09-03 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0003_auto_20190830_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_end_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_start_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car', to='CorrectionApp.Car'),
        ),
    ]
