# Generated by Django 2.2.4 on 2019-09-03 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0004_auto_20190903_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_end_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 3, 10, 50, 16, 885808)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_start_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 3, 10, 50, 16, 885808)),
        ),
    ]
