# Generated by Django 2.2.4 on 2019-09-05 07:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0008_auto_20190904_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='booking_end_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 9, 33, 12, 761080)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='booking_start_date',
            field=models.DateField(default=datetime.datetime(2019, 9, 5, 9, 33, 12, 761080)),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='is_approved',
            field=models.BooleanField(null=True),
        ),
    ]
