# Generated by Django 3.2.3 on 2021-05-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0012_auto_20210524_0537'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PostImage',
            new_name='CarImage',
        ),
    ]
