# Generated by Django 3.2.3 on 2021-05-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CorrectionApp', '0014_alter_car_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CarImage',
        ),
    ]
